micronaut:
  application:
    name: passforslag

access-token:
  issuer: "https://dev-uq-nu76u.eu.auth0.com/"
  audience: "w0LAP0uNFXZBNUlKp4YmLofmzCt2s4UD"

consul:
  client:
    registration:
      ip-addr: 172.16.13.14
      prefer-ip-address: true
      enabled: true
    defaultZone: "${CONSUL_HOST:127.0.0.1}:${CONSUL_PORT:8500}"
